# TS BUILDER CONFIG
FROM alpine
RUN apk add --update nodejs nodejs-npm
WORKDIR /app
COPY ["package.json", "package-lock.json*", "tsconfig.json", "jest.config.js", "./"]
RUN npm install
COPY src  src
COPY test  test
CMD ["npm", "run", "watch-test"]
