version: '3'
services:
  api:
    volumes:
      - ./src/:/app/src/
      - ./test/:/app/test/
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: crud_person__dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
